### ISSUE TITLE
Installer does not work on Windows XP

### ISSUE THREAD

**Issue by c0pperdragon** [c0pperdragon/EV3Basic#1]
The MSI creator built into Visual Studio 2013 is no longer comtabile with Windows XP.
Users with XP could still use the Small Basic with EV3Basic extension, but only when manually installing the files to the proper places. If there is indeed demand, I will patch up some ZIP file with the necessary files.

**Comment by shiftleftplusone** [comment]
da für Win XP nur Small Basic 1.0 möglich ist - ich würde trotzdem EV3Basic dann gerne auf XP nutzen!
Gruß
Helmut

**Comment by c0pperdragon** [comment]
I have now created a .zip file containing the necessary files to allow manual installation on Windows XP (which is no longer supported by Microsofts MSI installer). This can be found as "manual_installation.zip" in the releases folder. Just unpack the contents into the  ... /Microsoft/Small Basic/lib/  folder and start Small Basic. Or you can direcly use the EV3Explorer.
