### ISSUE TITLE
Communicate with pixy cam in small basic

### ISSUE THREAD

**Issue by flyboy74** [c0pperdragon/EV3Basic#11]
I have a pixy cam from charmed labs and can communicate with it fine in the EV3 icon based language using the block supplied from charmed labs. I want to be able to communicate with the pixy in small basic and was expecting the function sensor.communicateI2C would be able to do it but as of far havn't been able to make it work. Here is the porting info from charmed labs http://cmucam.org/projects/cmucam5/wiki/Porting_Guide

**Comment by c0pperdragon** [comment]
When you already succeeded in using the icon-based function block, you are probably using the special pixy cam version for lego mindstorms. For this, the manufacturer has designed a special protocol to be compatible with the lego brick. I found their protocol documentation at  

http://cmucam.org/documents/36

Using this information, it seems quite straight-forward to access all documented functions via the Sensor.CommunicateI2C command. 
Use I2C address of 1 (only one pixy cam can be used on a given lego port)  and send a query that consists of 1 or more bytes (depending on the first byte - a.k.a. 'address' in the pixy cam docu). In the same command call receive the proper number of bytes back (also depending on the first byte in the query). 

If you need more detailed help on making sense of the protocol specification, feel free to ask.

**Comment by flyboy74** [comment]
I have a signature programmed into pixy  and pixy in EV3 port 1 then ran following program but no luck.
While "True"
  TextWindow.WriteLine(Sensor.CommunicateI2C(1,1,1,6,80))
EndWhile

**Comment by flyboy74** [comment]
ok I have it working now. seems it must be an array to be able to pass to pixy. the following program works.
wirtebyte[0]= 80
While "True"
TextWindow.WriteLine(Sensor.CommunicateI2C(1,1,1,6,writebyte))
EndWhile
