### ISSUE TITLE
SmallBasic v1.3

### ISSUE THREAD

**Issue by aramperez** [c0pperdragon/EV3Basic#12]
The latest version of SmallBasic is v1.3 and it's available in the Microsoft Store. When I downloaded the .msi file, ran the installer, started SmallBasic and typed the example, I get a "LCD object not found" error. Can you help or do I have to install SmallBasic v1.2?

Thanks,
Aram

**Comment by c0pperdragon** [comment]
It seems the version 1.3 of Small Basic broke compatibility with the 
extensions. Until I can provide a new version of EV3 Basic, you should 
stick to Small Basic 1.2.
Reinhard

Am 10.08.2017 um 03:31 schrieb Aram Perez:

**Comment by aramperez** [comment]
Hi Reinhard,

Ok, downloaded and install SB v1.2. Everything is working now.

Thanks!
Aram

On Aug 11, 2017, at 05:45 AM, c0pperdragon <notifications@github.com> wrote:

It seems the version 1.3 of Small Basic broke compatibility with the 
extensions. Until I can provide a new version of EV3 Basic, you should 
stick to Small Basic 1.2.
Reinhard

Am 10.08.2017 um 03:31 schrieb Aram Perez:
