### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by c0pperdragon** [c0pperdragon/EV3Basic#17]
EV3Basic has documentation in quite some languages already: English, German, Spanish ,French, Russian and from the next version on in Polish as well. 
As the programing language and its libraries are evolving, these translations are often left behind and it is quite hard for me to keep them up to date. 
The most efficient way to handle this, would be if the individual language contributors could maintain the relevant files and directly provide all changes via pull-requests. The newest addition to the translations was done for the Polish language by the user @tojamrok in this way. 

The most relevant file is the Intellisense documentation, which is just a single .XML file in the Documentation folder named SmallBasicEV3Extension.[language].XML. This language dependent file will be used instead of the English SmallBasicEV3Extension.XML file that is auto-generated from the source code comments (you can find this .XML to use as a template in your EV3Basic installation directory).

Additionally, if you also want me to provide the user manual in your language, I would also need translations for the introductory chapters. These need to go into the Documentation/Resources folder and have just the name Manual[lanuage].txt  .  An english template is provided as Manual.txt .
Optionally (but this is probably not necessary, because it mainly concerns quite advanced topics), you could provide a translation for the Appendix.txt as well. If I have no translations for this I will just include the English version in the manual.

I have made a small tool to piece together the various parts and the information from the .XML to form a single HTML document. This I will always do for a new release.

**Comment by c0pperdragon** [comment]
This issue thread is also a perfect place to notify the translation contributors about things that have changed in EV3Basic which should also lead to an updated documentation.

So, here is a summary of the things I have added since release 1.2:
the whole library Byte 
the whole library F
Vector.Data
Small changes in the user manual introductory chapters
Changes in Appendix - I2C Tutorial
New Appendix - Advanced logic operation

Special note to @tojamrok: I have added Byte.ToLogic and Byte.L as well as Vector.Data while you did the Polish translations of all the other stuff.

**Comment by ddx-510** [comment]
Hi, I am Yankai's junior. May I ask where can I find the source code of the English version of  SmallBasicEV3Extension.XML, so that I can start on the Chinese translation.
Thank you!

**Comment by c0pperdragon** [comment]
Hello!
I have just created a release 1.2.5 that contains everything from the experimental version and all proper english documentation. This is the perfect point now to start a new translations. After installing the EV3Basic installer you should find the relevant .XML in   C:\Program Files (x86)\Microsoft\Small Basic\Lib   (or on a different path if you have installed it in a non-standard location).

I am not absolutely sure for which variant of Chinese you want to write the documentation, but I guess the file you create will probably be SmallBasicEV3Extension.zh-Hans.XML  (simplified chinese)
