### ISSUE TITLE
NET framework 3.5

### ISSUE THREAD

**Issue by lgneribonfim** [c0pperdragon/EV3Basic#19]
To install the Ev3 basic extension it requires NET framework 3.5. I can not install in a windows computer with NET framework 4.0 or later versions of NET framework.

**Comment by c0pperdragon** [comment]
I have built a new release that uses the .NET 4.5 framework exclusively. I hope this solves the problem.

**Comment by lgneribonfim** [comment]
Thank you very much! Now its working!
