### ISSUE TITLE
EV3.BatteryLevel opCode Problem

### ISSUE THREAD

**Issue by a10036gt** [c0pperdragon/EV3Basic#20]
Update: Success.Thanks Everybody~

The EV3.BatteryLevel is return the current charge level of the battery (0x12 GET_LBATT)
I want to get the Battery voltage ,and I modify the SmallBasicEV3Extension.dll and change c.CONST(0x12) to c.CONST(0x01),but the return value is wrong.
How to let the EV3 basic to read out the Battery voltage?
Thanks!

**Comment by a10036gt** [comment]
And how to edit compiler make LBATT to VBATT?Thanks!
subcall EV3.BATTERYLEVEL  // F
{
	OUT_F level

	DATA8 l8
	UI_READ GET_VBATT l8
	MOVE8_F l8 level
}

**Comment by a10036gt** [comment]
I Success ~~Thanks~~
subcall EV3.BATTERYLEVEL  // F
{
	OUT_F level
	DATAF l8
	UI_READ GET_VBATT l8
	MOVEF_F l8 level
}

**Comment by c0pperdragon** [comment]
Patching the SmallBasicEV3Extension and the compiler is a very hard-core solution.
You could get the same result easier:
There is a linear correlation between the percentage value delivered by EV3.BATTERYLEVEL and the actual voltage of the battery. Sensing the voltage is the only way to find out anything about the inner state of the battery. The true charge level is actually not linearly correlated to the voltage, but this is the best the device can do to figure out a rough estimation.

The conversion formula depends on the device being set to battery or accu (there is an option in the settings menu so the battery indicator makes more sense in each situation). 
I am not absolutely sure which voltages are mapped to 0% or 100% levels in each situation, but you could probably figure this out with a multimeter. The values between 0% and 100% linearly translate to the voltages in between.

**Comment by c0pperdragon** [comment]
I checked in the code of the lego firmware, and found the following voltage levels for 0% and 100% charge levels:

Battery:     6.2V - 7.5V
Accu:        7.1V  - 7.5V
 
Voltages beyond those values are always reported as 0% or 100% - so you can not detect if the battery has for example 8V.  This could probably make the whole scheme not as useful as I hoped for...

**Comment by a10036gt** [comment]
I use GET_VBATT can get the accu voltage of battery and same result of Electric meter.
It's very useful because 7.5V-8.4V always return 100%,but the motor speed was very difference between 2 voltages.
In fact the battery full charge always at 8.2-8.3xV

**Comment by iCheh** [comment]
Hey.
I do not speak English well and therefore I use an interpreter. I'm sorry if I get a bad translation.
I added a new EV3.BatteryVoltage function to your code.
 It seems useful to me because it allows you to recognize the voltage when it is more than 7.5 volts.
For example, when using the PID controller at 7.7 volts there will be one coefficients, at a voltage of 7.5 volts already different, and EV3.BatteryLevel function will not let you know when these coefficients need to be changed.

Can these changes be included in the next release?
[NewFunctionEV3BatteryVoltage.zip](https://github.com/c0pperdragon/EV3Basic/files/2369374/NewFunctionEV3BatteryVoltage.zip)


Which .msi package manager do you use?

Thank you.

**Comment by a10036gt** [comment]
Your solution code was same as me.
I also add ampere.

**Comment by iCheh** [comment]
Maybe an ampere is useful too. With a large increase in the current consumption and a decrease in the rotation of the motors, we can indirectly say that the robot rises up the mountainside

**Comment by c0pperdragon** [comment]
In the next release, I will integrate the properties EV3.BatteryVoltage and EV3.BatteryCurrent for such sophisticated use cases.

**Comment by a10036gt** [comment]
Thanks!

**Comment by iCheh** [comment]
Thank You!
