### ISSUE TITLE
EV3Explorer 1.2.8 USB connection

### ISSUE THREAD

**Issue by iCheh** [c0pperdragon/EV3Basic#25]
Good afternoon.
Sorry for my bad english.

There was a problem. EV3Explorer 1.2.8 does not connect with Brick EV3 via USB, just sees it (OS Windows 10, USB 3.0 port). Only Bluetooth works.
At the same time, on another computer (OS Windows 7 old USB port) everything works well.

Can you say what could be the reason? 
Thank you.

**Comment by c0pperdragon** [comment]
That is of course very hard to tell from the distance. 
Maybe there is another program connected to the brick that blocks the EV3Explorer from using the connection? The original Lego software for example.
If that is not the case, you could try to install the version 1.2.6 of EV3 Basic (uninstall 1.2.8 first), which used an earlier version of the .NET framework. Maybe the newest version has some compatibility issue. This would be very important for me to know.

**Comment by c0pperdragon** [comment]
Could you also provide me with a screenshot, what the EV3Explorer actually displays (I guess it would show a dialog box to select a connection method from) and what exactly happens then.

**Comment by iCheh** [comment]
Other programs are not running, only EV3Explorer. The connection dialog is empty, it does not see the brick connected via USB 3.0. Sees only if the brick is connected via bluetooth.

I think it has to do with USB ports. The old USB port works on one computer, the new USB 3.0 port does not work on another computer.

At the same time, the original Lego software works fine on two computers and the brick is connected via the old USB and the new USB 3.0.

Ok. I will make a screenshot a bit later.

**Comment by iCheh** [comment]
I will disturb you again.
I do not know what it is connected with, but EV3Explorer 1.2.8 suddenly saw my EV3 brick via USB. And now there is no connection problem. I myself didn’t do anything, just rebooted the brick and the laptop and it all worked. This is a bit strange, but as they say here - "It works, do not touch it." :)

**Comment by c0pperdragon** [comment]
I sometimes have problems with the USB connection, when I connect the already running EV3 brick to the PC, or when unplugging it (could lead to crashes of the brick).  Safest option is to always first connect the brick and then power it on (and first power it down before disconnecting).  
Maybe this behavior caused your issues too.
