### ISSUE TITLE
Multiple file project

### ISSUE THREAD

**Issue by timmmerlan** [c0pperdragon/EV3Basic#30]
Hello,
is it possible to structure a project in multiple files of source code using commands from each other? I have a large project and would like to have a bit of structure in the source code by e.g. move some Sub-functions that aren't edited that often, to another source file.
Thanks for your help!
Tim

**Comment by c0pperdragon** [comment]
This would of course be really a very usable feature. But I really want to keep my compiler compatible with the Small Basic environment, and there this is also not possible. 

Introducing incompatible extensions to the EV3 Basic compiler would lead to a split system where code from one flavour would no longer work with the other flavour.

Sorry.
