### ISSUE TITLE
Gyro Angle Rate Does Not Read Out

### ISSUE THREAD

**Issue by ghost** [c0pperdragon/EV3Basic#31]
I modified the program in the documentation to read out the gyro rate.

```
Sensor.SetMode(2,1)  'measure angle rate
While "True"
  LCD.StopUpdate()
  LCD.Clear()
  LCD.Write(100,80,Sensor.ReadRawValue(2, 1) + " deg/s")
  LCD.Write(100,90,EV3.Time)
  LCD.Update()
EndWhile
```

The LCD only displays "0 deg/s" and the brick run time. The display does work for displaying the gyro angle when the mode is set to 0.

Additionally, the gyro seems to add 2-3 deg of clockwise bias every time I execute a +90 rotation and then a -90 rotation.

**Comment by Technonati** [comment]
Also, when I run this, it seems that when I rotate the gyro 90 deg CW and then back, it adds 2-3 deg of clockwise bias, so after 10 right turns and left turns, the gyro reads about 20 or so deg.

**Comment by c0pperdragon** [comment]
I am not sure myself about the gyro sensor, as I do not have one myself. Maybe the ReadRaw call delivers the result your are looking for at a different index. 
Try ReadRawValue(2,0) or ReadRawValue(2,2) instead.

**Comment by ghost** [comment]
We'll try it out and see what happens. Thanks.
