### ISSUE TITLE
Blue tooth 

### ISSUE THREAD

**Issue by OutOfTheBots** [c0pperdragon/EV3Basic#33]
Is there any plans to add support for EV3 to EV3 blue tooth coms? Many of the kids are doing project where there is more than 1 brick and the bricks need to be able to works together by sending data to each other via blue tooth.

**Comment by c0pperdragon** [comment]
The Mailbox facility is already provided for this kind of communication.

**Comment by OutOfTheBots** [comment]
Can you please point me to the docs that explain how to program this. Thanks :)

**Comment by OutOfTheBots** [comment]
Ok I have found the manual with all the needed info. Thanks for building and maintaining EV3Basic :)
