### ISSUE TITLE
Does EV3 Explorer support compiling custom dlls?

### ISSUE THREAD

**Issue by IgneousRed** [c0pperdragon/EV3Basic#36]
I made a custom dll that uses EV3Basic, and it runs fine in "PC mode" but when trying to compile it, I get an error: "Undefined command: CLASS.METHOD at rows:colums"
So my question is does EV3 Explorer support compiling custom dlls? if so, Are there some additional steps?

**Comment by c0pperdragon** [comment]
Sorry. You can not compile custom DLLs down to the EV3 brick. It is a completely different operating system and processor architecture than your regular PC.

**Comment by IgneousRed** [comment]
Alright... Tnx
