### ISSUE TITLE
contact email: reinhard.grafl (at) aon.at gibt es nicht

### ISSUE THREAD

**Issue by shiftleftplusone** [c0pperdragon/EV3Basic#4]
hallo,
deine contact email: reinhard.grafl (at) aon.at gibt es nicht
(Mail delivery failed: returning message to sender)

**Comment by c0pperdragon** [comment]
Bitte nicht meine email-addresse ohne jede Tarnung posten. Kriege eh schon genug Spam.

**Comment by c0pperdragon** [comment]
Und die angegebene Addresse (natürlich mit @ statt (at) funktioniert für mich super).

**Comment by shiftleftplusone** [comment]
das ist ja komisch. habs 3x probiert, 3x kams per mailer demon zurück 3x falsch kopiert und ersetzt?
ich probiers nochmal
Vllt ist wirklich 1 Zeichen beim löschen +einsetzen vom @ falsch drin geblieben

**Comment by shiftleftplusone** [comment]
ja, sieht so aus als hätte ich 1x eine KLammer drin gelassen und 2x das l von grafl mit gelöscht.
Das ist auf nem kleinen Bildschirm nicht immer einfach mit dem @ erstetzen :-/

dies war die Nachricht:

Hallo Reinhard,
ich möchte nun doch versuchen, den EV3 mit Arduinos per I2C zu verbinden. Leider habe ich zuhause nur WinXP, lediglich mein PC an der Arbeitsstelle hat Win7, wo ich "schnell mal" was testen kann. Beim 1. Release mit Small Basic 1.0 hat noch alles geklappt, aber mit 1.1 läuft EV3Basic la leider nicht mehr.

Könntest du bitte wieder eine alte oder eine gepatchte Version für XP zum Download einstellen?

Danke schon mal im vorraus!

Viele Grüße

Helmut Wunder aka "HaWe"

PS,
hier sind die beiden EV3Basic Projekt-Threads: 

http://www.mindstormsforum.de/viewtopic.php?f=25&p=67578#p67578

http://www.mindstormsforum.de/viewtopic.php?f=25&t=8673

H.

**Comment by c0pperdragon** [comment]
Hi!

Hoffe, diese Nachricht kommt an. Ich habe dir ein .ZIP zusammengestellt 
und auf github raufgeladen. Erklärung ist im
issue "Installer does not work on Windows XP" zu finden.

Gutes Gelingen,

Reinhard

Am 23.09.2015 um 20:19 schrieb VogonJeltz:

**Comment by shiftleftplusone** [comment]
danke!

A-Bär...:
wo ist der Releases Ordner auf https://github.com/c0pperdragon/EV3Basic ?

wenn ichs dann recht verstehe:
Basis 1.0 installieren nach c:\programme\smallbasic
und dann den kompletten Inhalt des zip files da blind rein kopieren?

**Comment by c0pperdragon** [comment]
Zu den releases kommst du von der Projektseite mit dem menüpunkt 
"releases" (mittig über dem grünen balken).
Und der Inhalt vom zip gehört in das bereits bestehende lib/ - 
Verzeichnis innerhalb von Small Basic.

Reinhard

Am 24.09.2015 um 09:52 schrieb VogonJeltz:

**Comment by shiftleftplusone** [comment]
aaah...! danke!  :)

Gruß
Helmut
