### ISSUE TITLE
 EV3BasicInstaller 1.07 not working with SmallBasic 1.2

### ISSUE THREAD

**Issue by lsa-pilot** [c0pperdragon/EV3Basic#5]
The links to SmallBasic 1.1 download are broken, I found and installed SmallBasic 1.2 on my Windows 7 (64-bit) system.  After downloading and installing EV3BasicInstaller.msi the intellisense does not work.

**Comment by c0pperdragon** [comment]
Thank you for telling me about this new Small Basic version and the 
compatibility problems.
I have just created a new release of EV3Basic to address this issue.
https://github.com/c0pperdragon/EV3Basic/releases

best regards,
Reinhard

Am 04.10.2015 um 04:56 schrieb lsa-pilot:

**Comment by lsa-pilot** [comment]
Hi Reinhard, 
your fix works, I was able to control the motors of the EV3.
Many thanks for this and a very nice software extension to teach programming.
Alex
