### ISSUE TITLE
ev3 basic to Visual studio

### ISSUE THREAD

**Issue by nowark** [c0pperdragon/EV3Basic#6]
Helo,
how did U make this work in Visual studio?
I can write some program in small basic but when i try to convert it, many error apears.
1. I change the version of frame work to 4.5
![vs error](https://cloud.githubusercontent.com/assets/16730912/12614201/a25a5f12-c4fe-11e5-8811-29cc5c5e4f41.jpg)

please help me

**Comment by c0pperdragon** [comment]
Hi!

I am no sure, what you try to do. I guess, you wrote some program with 
Small Basic and and were able to run it.
For some reasons Small Basic has this "Convert" button, to turn the 
whole thing into a visual studio project, but I have not supported this 
for my EV3 extension (I am not even sure, this works in any case).

The only sensible thing to do with EV3-Basic programs, except of running 
it with Small Basic, is to compile it to be run directly on the EV3 
brick. Please use the EV3-Explorer to do this.

Reinhard

Am 27.01.2016 um 14:03 schrieb nowark:

**Comment by nowark** [comment]
helo,

Thanks for your message, i will stick with small basic then

best regard
