### ISSUE TITLE
"Russian Documentation" als Überschrift verwirrend

### ISSUE THREAD

**Issue by shiftleftplusone** [c0pperdragon/EV3Basic#7]
hallo,

das große
"Russian Documentation"

verwirrt viele potentielle User, wenn sie die deutsche oder die englische Anleitung bzw, Download oder Handbuch suchen.

Vielleicht wäre es besser, es als

"Jetzt zusätzlich / additionally Russian Documentation"

zu übetschreiben

**Comment by c0pperdragon** [comment]
Changed the caption of the release.
