### ISSUE TITLE
Other language support

### ISSUE THREAD

**Issue by nokapcha** [c0pperdragon/EV3Basic#9]
What language I can use with the help of EV3 Basic?
For examle, we can use EV3 Basic with PascalABC.Net (http://pascalabc.net/en/download)
refering SmallBasicEV3Extension library and EV3Communication library. After that we write simple code 

```
uses EV3BasicCompiler,
EV3Communication;

begin
    SmallBasicEV3Extension.Motor.Start('BC', 100);
    Sleep(1000);
end.
```

Then robot start in Small basic mode and rotate the motors for 1 second
Of cource, we can use other .Net landuages, but how we can convert this program into a form that can be executed directly on the brick?

**Comment by c0pperdragon** [comment]
There is no support for compiling anything to the EV3 brick other than Small Basic code. And even then not all language featues of Small Basic can be perfectly supported. 
The lego byte code interpreter (a.k.a. virtual machine) is so restricted that its possibilities just about match the features of Small Basic, but not much more. Compiling a general .NET byte code exectuable to this target is totally out of the question.
